server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_recruit?characterEncoding=UTF8
    username: root
    password: zhouhai
  jpa: 
    database: MySQL
    show-sql: true
